LSTM_AE:
  feature_num: 5
  rnn_type: 'LSTM'
  rnn_inp_size: 64
  rnn_hid_size: 128
  nlayers: 2
  dropout: 0.1
  res_connection: false
  return_hiddens: false
  # RevIN 설정
  use_revin: false          # RevIN 미사용
  revin_affine: true
  revin_subtract_last: false
  revin_eps: 0.00001
